on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Run PSScriptAnalyzer
        shell: pwsh
        run: |
          $results = Invoke-ScriptAnalyzer -Path ./A-P2P.ps1 -Recurse -Severity Error
          if ($results) {
              $results | Format-Table
              exit 1
          } else {
              Write-Host "Success: No critical script errors found."
          }
